pipeline:
  - name: Build
    script: python setup.py sdist bdist_wheel
  - name: Test
    script: pytest tests/ --junitxml=report.xml
  - name: Lint
    script: flake8 src/
  - name: Deploy
    script: ./deploy.sh
